### PR TITLE
FrameDur

### PR DESCRIPTION
**Pull request by findmory**
adds the ability to specify a 'frameDur' which is how long to hold each frame in the GIF that is being created.  a frameDur of 10 will hold the frame for 1 second

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by pliablepixels** [comment]
hi there, if I understand the code correctly, it is essentially duplicating the frame X times to meet frameDur. This approach essentially increases the memory X fold - is that correct ? I'm struggling to keep memory in check.

**Comment by findmory** [comment]
Hi yes you are correct it would increase the size of the file.  To me it seems worth it to have the customizable flexibility of how the animation plays back.

**Comment by stevenfabre** [comment]
Hi there, thanks for putting this awesome library together.

Is this going to be merged anytime soon? I really need that for my project and was going to suggest similar change myself.

Thanks

**Comment by gfranko** [comment]
I'm looking into this now... will be releasing an ES6 re-write today

**Pull request closed without merging**
