### PR TITLE
HTML5 Video Element Offset Option

### PR DESCRIPTION
**Pull request by cranberryofdoom**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by cranberryofdoom** [comment]
Oh, of course!

**Comment by cranberryofdoom** [comment]
Okay! Just signed!

**Comment by cranberryofdoom** [comment]
Hm, I just checked Safari and the option doesn't seem to be setting the currentTime like it is in FF or Chrome. Just figured out a fix for this. Pushing it up in a bit.

**Pull request merged**
